### PR TITLE
Shanoir-issue#1159 processed dataset bug

### LINKED ISSUE #1159: [Bug | processed datasets] Error while uploading processed datasets
An error occurs sometime when uploading processed dataset.

### PR DESCRIPTION
**Pull request by jcomedouteau**
Processed dataset is now working.

Closes #1159

### CODE REVIEW

File: shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/ShanoirMetadataRepositoryImpl.java [hunk 1]
```diff
@@ -218,8 +223,15 @@ public ShanoirMetadata findOneSolrDoc(Long datasetId) {
...
-
+		
+		List<ShanoirMetadata> processedResult = processedQuery.getResultList();
+		
+		if (!processedResult.isEmpty()) {
+			return processedResult.get(0);
+		}
+		
 		if (result.size() != 1) {
+			System.err.println("Solr query returned multiple result for a single query. Please check database consistency.");
```
Comment (Nunien) [inline shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/ShanoirMetadataRepositoryImpl.java:234]: Why not use LOG.error() ?

Comment (jcomedouteau) [reply shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/ShanoirMetadataRepositoryImpl.java:234]: Good question ! I'm changing it

Comment (jcomedouteau) [reply shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/ShanoirMetadataRepositoryImpl.java]: It's OK

**Review by Nunien — APPROVED** [review]
