### PR TITLE
issue#3394: Fix for failing bootstrap.sh execution

### LINKED ISSUE #3394: Bootstrap script fails
The bootstrap script fails after the introduction of the draft studies feature.

### PR DESCRIPTION
**Pull request by fragkiadamis**
Insert `study_extra_details` data into SQL initialization scripts

How to test:
Just execute the `./bootrapt --clean` command on the project's root dir (it should install without any errors).
No need for qualif deployment, since the fix is about the local installation of shanoir-ng

Should be merged before next release to avoid any issues with the clean installations from the users

Close #3394

### CODE REVIEW

File: shanoir-ng-studies/src/main/java/org/shanoir/ng/study/model/Study.java [hunk 1]
```diff
@@ -100,6 +100,7 @@ public class Study extends HalEntity {
     private boolean downloadableByDefault;
 
     /** End date. */
+    @NotNull
```
Comment (DuckflipXYZ) [inline shanoir-ng-studies/src/main/java/org/shanoir/ng/study/model/Study.java]: There are studies with null values in ofsep (I did not check for neurinfo). I might raise a lack of consistency, I'm not sure how to deal with it

**Review by DuckflipXYZ — COMMENTED** [review]
It works, all goods except one tiny comment.

**Review by michaelkain — APPROVED** [review]
