### PR TITLE
#2309-download-firefox-bug

### LINKED ISSUE #2309: NIfTI massive download KO with Firefox
When downloading multiple NIfTI in Solr view with Firefox, the resulting ZIP archive contains only one .nii.gz (first selected dataset ?).

In browser console, there is multiple ` /massiveDownload` call instead of one

### PR DESCRIPTION
**Pull request by jcomedouteau**
Closes #2309 

How to test:
- Download a dataset from firefox with developper tool open -> Only one call is made to the back

I let the UUID to avoid potential errors.
I also remove the "delete" log.

### CODE REVIEW

File: shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java [hunk 1]
```diff
@@ -207,7 +208,9 @@ public void massiveDownload(String format, List<Dataset> datasets, HttpServletRe
 	private void reconvertToNifti(String format, HttpServletResponse response, Long converterId, Dataset dataset, SimpleDateFormat formatter, List<URL> pathURLs, DatasetDownloadError downloadResult, String subjectName, ZipOutputStream zipOutputStream) throws RestServiceException, IOException {
 		File userDir = DatasetFileUtils.getUserImportDir("/tmp");
 		String tmpFilePath = userDir + File.separator + dataset.getId() + "_" + format;
-		File sourceFolder = new File(tmpFilePath + "-" + formatter.format(new DateTime().toDate()));
+		UUID uuid = UUID.randomUUID();
```
Comment (youennmerel) [inline shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java:211]: We could inline this I think 
``` java
File sourceFolder = new File(tmpFilePath + "-" + UUID.randomUUID());
```

File: shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java [hunk 2]
```diff
@@ -230,12 +233,15 @@ private void reconvertToNifti(String format, HttpServletResponse response, Long
 
 				String datasetFilePath = res.getAbsolutePath();
 				String fileName = res.getName();
-				boolean toGzip = datasetFilePath.endsWith(".nii");
+				String extension = fileName.endsWith(".nii.gz") ? ".nii.gz" : "." + FilenameUtils.getExtension(fileName);
+				String fileNameToSet = getDatasetFileName(dataset) + extension;
+
+				boolean toGzip = fileNameToSet.endsWith(".nii");
```
Comment (youennmerel) [inline shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java:239]: I would use `extension` here.
``` java
boolean toGzip = extension == ".nii"

```

File: shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java [hunk 3]
```diff
@@ -230,12 +233,15 @@ private void reconvertToNifti(String format, HttpServletResponse response, Long
...
 
 				// Gzip file if necessary in order to always return a .nii.gz file
 				if (toGzip) {
```
Comment (youennmerel) [inline shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java:242]: in fact I would directly test it here :
``` java
if (extension == ".nii") {
```

File: shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java [hunk 4]
```diff
@@ -255,8 +261,8 @@ private void reconvertToNifti(String format, HttpServletResponse response, Long
 				}
 			}
 		} finally {
-			LOG.error("deleting directory " + sourceFolder.getAbsolutePath());
-			FileUtils.deleteDirectory(sourceFolder);
+			LOG.info("deleting directory " + sourceFolder.getAbsolutePath());
```
Comment (youennmerel) [inline shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java:264]: You could use placeholder here :
``` java 
LOG.info("Deleting directory [{}]", sourceFolder.getAbsolutePath());
```

**Review by youennmerel — COMMENTED** [review]
Hi JC,
Some small, petty remarks.

**Review by youennmerel — APPROVED** [review]
Pb with Chrome will be solved in https://github.com/fli-iam/shanoir-ng/pull/2328
