### PR TITLE
Fix async loading of prefilled values in dataset processing form

### LINKED ISSUE #3104: Import processed dataset bug
When trying to import a processed dataset in Shanoir, we need to fill out a form with details such as the study, subject, type, name, etc. After that, we must create a processed dataset entity to link the imported dataset with an input dataset and optionally an output dataset.

In this form, the study field should be preselected based on the previous form and should be disabled to prevent modification. However, due to a bug, the study is not preselected, while the field remains disabled, making it impossible to import the dataset from the UI.

Image

### PR DESCRIPTION
**Pull request by fragkiadamis**
Closes #3104

### CODE REVIEW

**Review by DuckflipXYZ — APPROVED** [review]
Clean

File: shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.ts [hunk 1]
```diff
@@ -123,23 +123,22 @@ export class DatasetProcessingComponent extends EntityComponent<DatasetProcessin
...
-            }
+        return Promise.all([
+            this.breadcrumbsService.currentStep.getPrefilledValue('study').then(res => this.prefilledStudy = res),
+            this.breadcrumbsService.currentStep.getPrefilledValue('subject').then(res => this.prefilledSubject = res)
+        ])
+        .then(([study, subject]) => {
+            this.prefilledStudy = study;
+            this.prefilledSubject = subject;
+
+            this.studyOptions = [new Option(this.prefilledStudy, this.prefilledStudy.name)];
```
Comment (DuckflipXYZ) [inline shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.ts]: I'm not sure that this line is still required. Can you confirm ?

File: shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.ts [hunk 2]
```diff
@@ -123,23 +123,22 @@ export class DatasetProcessingComponent extends EntityComponent<DatasetProcessin
...
+            this.study = this.prefilledStudy;
+            this.datasetProcessing.studyId = this.study?.id;
+
+            this.subjectOptions = [new Option(this.prefilledSubject, this.prefilledSubject.name)];
```
[the remark this answers is not in the document]
Comment (fragkiadamis) [reply shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.ts]: Those are necessary too to populate the DatasetProcessingComponent, as well as to populate the subject select box field.

File: shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.ts (hunk 1 above)
Comment (DuckflipXYZ) [reply shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.ts]: Ok, I was wondering as we are not able to select a new study neither subject, as they are readonly
